Tezos hooks with TypeScript
tezos-israel/tezos-react-hooks pull request #5
Opened 2020-09-02 14:34 UTC by claudebarde

2020-09-02 15:11 UTC, chiptus requested changes

2020-09-02 15:11 UTC, chiptus commented on use-balance.ts
> +export function useBalance(address: string = "") {
shouldn't we have return types for the hooks?

2020-09-02 15:28 UTC, chiptus requested changes

2020-09-02 15:28 UTC, chiptus commented on use-contract.ts
> +    console.log(contract);
remove console.log

2020-09-02 15:28 UTC, chiptus commented on use-contract.ts
> +    const interval = setInterval(async () => loadStorage(contract), 6000);
isn't 6 seconds too low? I believe a minute is enough, as the blockchain updates every one minute, no?

2020-09-02 15:28 UTC, chiptus commented on use-balance.ts
> +  const [balance, setBalance]: [number, (p: number) => void] = useState();
useState<number> doesn't work? like in use-contract?

2020-09-02 15:37 UTC, claudebarde commented on use-contract.ts
> +    console.log(contract);
Fixed

2020-09-02 15:40 UTC, claudebarde commented on use-balance.ts
> +  const [balance, setBalance]: [number, (p: number) => void] = useState();
This only enforces to pass a number for the balance in `setBalance` (and not a string for example). Not absolutely necessary though, just to make TS throw an error if anything else but a number is passed. Now that I think about it, the user doesn't have access to `setBalance` so we can relax it :)

2020-09-03 08:46 UTC, chiptus approved these changes

2020-09-03 08:47 UTC, merged